# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncAbilityTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_rec', models.BooleanField(default=False)),
                ('test_link', models.URLField(max_length=500)),
                ('test_instruct', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='TestParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_text', models.CharField(max_length=200)),
                ('parameter_testkey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FuncAbilityTest')),
            ],
        ),
    ]
