# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_funcabilitytest_testparameter'),
    ]

    operations = [
        migrations.AddField(
            model_name='testparameter',
            name='parameter_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testparameter',
            name='parameter_testkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.FuncAbilityTest'),
        ),
    ]
