# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170222_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='test_rec',
            new_name='isRecommended',
        ),
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='test_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='test_instruct',
            new_name='pdfLink',
        ),
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='test_video',
            new_name='videoLink',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='medication_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_answer',
            new_name='isKey',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_why',
            new_name='reason',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='testparameter',
            old_name='parameter_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='testparameter',
            old_name='parameter_risk',
            new_name='risk',
        ),
        migrations.RenameField(
            model_name='testparameter',
            old_name='parameter_testkey',
            new_name='testKey',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_key',
        ),
    ]
