# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170227_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DummyModel',
        ),
    ]
