# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-02 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_delete_dummymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='isRecommended',
            new_name='is_recommended',
        ),
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='pdfLink',
            new_name='pdf_link',
        ),
        migrations.RenameField(
            model_name='funcabilitytest',
            old_name='videoLink',
            new_name='video_link',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='isKey',
            new_name='is_key',
        ),
        migrations.RenameField(
            model_name='testparameter',
            old_name='testKey',
            new_name='test_key',
        ),
    ]
