# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 09:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20170302_0337'),
    ]

    operations = [
        migrations.CreateModel(
            name='GpiCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gpicode',
            name='med_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Medication'),
        ),
    ]
